// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eaxpkyxlykbvhcxekcae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVheHBreXhseWtidmhjeGVrY2FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA5Mzk2NTQsImV4cCI6MjA1NjUxNTY1NH0.bGpNUSF4XP2xv8itpy7zu6RDtHIlOnfeamwkaMs9s_4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);